/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Color;
import java.awt.Component;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JComponent;
import javax.swing.JList;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import model.CompanyDAO;
import model.RoleDAO;
import model.UsersDAO;

/**
 *
 * @author VictorManuel
 */
public class vUsuariosAdmin extends javax.swing.JFrame {

    JTable tabla;
    /**
     * Creates new form vUsuariosAdmin
     */
    public vUsuariosAdmin() {
        initComponents();

        jTextField1.setOpaque(false);
        jTextField1.setBackground(new Color(0, 0, 0, 0));

        jTextField2.setOpaque(false);
        jTextField2.setBackground(new Color(0, 0, 0, 0));

        jTextField3.setOpaque(false);
        jTextField3.setBackground(new Color(0, 0, 0, 0));

        jTextField4.setOpaque(false);
        jTextField4.setBackground(new Color(0, 0, 0, 0));

        jTextField5.setOpaque(false);
        jTextField5.setBackground(new Color(0, 0, 0, 0));

        jTextField6.setOpaque(false);
        jTextField6.setBackground(new Color(0, 0, 0, 0));

        jTextField7.setOpaque(false);
        jTextField7.setBackground(new Color(0, 0, 0, 0));

        jTextField8.setOpaque(false);
        jTextField8.setBackground(new Color(0, 0, 0, 0));

        jTextField9.setOpaque(false);
        jTextField9.setBackground(new Color(0, 0, 0, 0));

        jTextField10.setOpaque(false);
        jTextField10.setBackground(new Color(0, 0, 0, 0));

        jTextField11.setOpaque(false);
        jTextField11.setBackground(new Color(0, 0, 0, 0));

        jPasswordField1.setOpaque(false);
        jPasswordField1.setBackground(new Color(0, 0, 0, 0));
        
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        jTable1.setShowGrid(false);
        
        jTable1.setDefaultEditor(Object.class, null);

        ArrayList<String> listroles = new ArrayList<String>();
        listroles = llenarListaRoles();
        for (int i = 0; i < listroles.size(); i++) {
            jComboBox2.addItem(listroles.get(i));
        }

        ArrayList<String> listcompanys = new ArrayList<String>();
        listcompanys = llenarListaCompanys();
        for (int i = 0; i < listcompanys.size(); i++) {
            jComboBox3.addItem(listcompanys.get(i));
        }
        
        this.llenarTabla();
    }
    
    public void llenarTabla() {
        UsersDAO u = new UsersDAO();
        DefaultTableModel dfm = new DefaultTableModel();
        tabla = this.jTable1;
        tabla.setModel(dfm);
        
        dfm.setColumnIdentifiers(new Object[]{"Codigo", "Usuario", "Telefono", "Colonia", "Calle", "Numero", "CP", "Ciudad", "Estado", "Email" , "Celular"});
        ResultSet rs = u.getUsers();

        try {
            while (rs.next()) {
                dfm.addRow(new Object[]{rs.getInt("userid"), rs.getString("username"),rs.getString("phone"), rs.getString("neigborhood"),rs.getString("street"), rs.getString("streetnumber"),rs.getString("zipcode"), rs.getString("city"),rs.getString("state"), rs.getString("email"), rs.getString("cellphone")});
            }
        } catch (Exception e) {
            System.out.println("Error al cargar los datos: " + e.getMessage());
        }
    }
    
    

    public ArrayList<String> llenarListaCompanys() {
        ArrayList<String> list = new ArrayList<String>();
        CompanyDAO con = new CompanyDAO();
        ResultSet rs = con.getCompanys();
        try {
            while (rs.next()) {
                list.add(rs.getString("companyname"));
            }
        } catch (Exception e) {
            System.out.println("Error al cargar los datos");
        }

        return list;
    }

    public ArrayList<String> llenarListaRoles() {
        ArrayList<String> list = new ArrayList<String>();
        RoleDAO rol = new RoleDAO();
        ResultSet rs = rol.getRoles();
        try {
            while (rs.next()) {
                list.add(rs.getString("rolename"));
            }
        } catch (Exception e) {
            System.out.println("Error al cargar los datos");
        }

        return list;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField11 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 840, 290));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/eliminarnormal.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton4.setIconTextGap(-3);
        jButton4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/eliminarclick.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/editarnormal.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton3.setIconTextGap(-3);
        jButton3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/editarclick.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/nuevonormal.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.setIconTextGap(-3);
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/nuevoclick.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jPasswordField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPasswordField1.setBorder(null);
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 11, 280, 30));

        jComboBox3.setBackground(new java.awt.Color(181, 181, 181));
        jComboBox3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 242, 260, -1));

        jComboBox2.setBackground(new java.awt.Color(181, 181, 181));
        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 242, 230, -1));

        jComboBox1.setBackground(new java.awt.Color(181, 181, 181));
        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 242, 70, -1));

        jTextField11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField11.setBorder(null);
        getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 301, 220, 30));

        jTextField10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField10.setBorder(null);
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 194, 330, 30));

        jTextField9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField9.setBorder(null);
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 194, 340, 30));

        jTextField8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField8.setBorder(null);
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 149, 330, 30));

        jTextField7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField7.setBorder(null);
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 149, 320, 30));

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField6.setBorder(null);
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(683, 101, 190, 30));

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField5.setBorder(null);
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 101, 100, 30));

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField4.setBorder(null);
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 100, 240, 30));

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField3.setBorder(null);
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 53, 330, 30));

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField2.setBorder(null);
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 54, 300, 30));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField1.setBorder(null);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 12, 310, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fondouseradmin.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        RoleDAO r = new RoleDAO();
        CompanyDAO co = new CompanyDAO();

        int roleid = 0;
        int companyid = 0;
        String gender = (String) jComboBox1.getSelectedItem();

        r.setRolename((String) jComboBox2.getSelectedItem());
        ResultSet rs = r.getRoleByName();
        try {
            while (rs.next()) {
                roleid = rs.getInt("roleid");
            }
        } catch (Exception e) {
            System.out.println("Error al cargar los datos");
        }

        co.setCompanyname((String) jComboBox3.getSelectedItem());
        ResultSet rr = co.getCompanyByName();
        try {
            while (rr.next()) {
                companyid = rr.getInt("companyid");
            }
        } catch (Exception e) {
            System.out.println("Error al cargar los datos");
        }

        String username = jTextField1.getText();
        String password = String.valueOf(jPasswordField1.getPassword());
        String phone = jTextField2.getText();
        String neigborhood = jTextField3.getText();
        String street = jTextField4.getText();
        String streetnumber = jTextField5.getText();
        String zipcode = jTextField6.getText();
        String city = jTextField7.getText();
        String state = jTextField8.getText();
        String email = jTextField9.getText();
        String cellphone = jTextField10.getText();

        if (username.equals("") || password.equals("") || phone.equals("") || neigborhood.equals("") || street.equals("") || streetnumber.equals("") || zipcode.equals("") || city.equals("") || state.equals("") || email.equals("") || cellphone.equals("")) {
            javax.swing.JOptionPane.showMessageDialog(null, "Es necesario rellene todos los campos");
        } else {
            UsersDAO users = new UsersDAO();
            users.setUsername(username);
            users.setPassword(password);
            users.setPhone(phone);
            users.setNeigborhood(neigborhood);
            users.setStreet(street);
            users.setStreetnumber(streetnumber);
            users.setZipcode(zipcode);
            users.setCity(city);
            users.setState(state);
            users.setEmail(email);
            users.setCellphone(cellphone);
            users.setGender(gender.charAt(0));
            users.setRoleid(roleid);
            users.setCompanyid(companyid);
            
            if (users.newUsers()) {
                this.llenarTabla();
                jTextField1.setText("");
                jPasswordField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                jTextField4.setText("");
                jTextField5.setText("");
                jTextField6.setText("");
                jTextField7.setText("");
                jTextField8.setText("");
                jTextField9.setText("");
                jTextField10.setText("");
                
                
                System.out.println("Se inserto correctamente");
            } else {
                System.out.println("Problemas en la inserción");
            }
        }

        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vUsuariosAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vUsuariosAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vUsuariosAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vUsuariosAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vUsuariosAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
